Restaurante/Models/ErrorViewModel.cs
using System;

namespace Restaurante.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Restaurante/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Restaurante.Models {
    public class Pedido {
        public Pedido() {
            Data = DateTime.Now;
        }

        [Key]
        public int Id { get; set; }
        public string Nome { get; set; }

        public int Mesa { get; set; }

        public string Pratos { get; set; }

        public int QtdPratos { get; set; }

        public string Bebidas { get; set; }

        public int QtdBebidas { get; set; }

        public string Sobremesas { get; set; }

        public int QtdSobremesas { get; set; }

        public DateTime Data { get; set; }

    }
}

Restaurante/Models/RestauranteContext.cs
using Microsoft.EntityFrameworkCore;

namespace Restaurante.Models {
    public class RestauranteContext : DbContext {
        public RestauranteContext(DbContextOptions<RestauranteContext> options) : base(options) {

        }

        public DbSet<Pedido> Pedidos { get; set; }
    }
}

Restaurante/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Restaurante.Models;

namespace Restaurante.Controllers {
    public class HomeController : Controller {
        public IActionResult Index() {
            return View();
        }

      

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Restaurante/Controllers/RestauranteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Restaurante.Interface;
using Restaurante.Models;
using Restaurante.Repository;

namespace Restaurante.Controllers
{
    public class RestauranteController : Controller
    {
        private readonly IPedidoRepository _pedidoRepository;
        public RestauranteController(IPedidoRepository pedidoRepository) {
            _pedidoRepository = pedidoRepository;
        }

        [HttpGet]
        public ActionResult Pedidos() {
            return View(_pedidoRepository.GetAll());
        }

        [HttpPost]
        public ActionResult Pedidos(Pedido pedido) {
            _pedidoRepository.Add(pedido);

            return View(_pedidoRepository.GetAll());
        }

    }
}

Restaurante/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pedidos Mesa";
}

@model Restaurante.Models.Pedido

<div class="row">
    <div class="formularioCadastro">
        @using (Html.BeginForm("Pedidos", "Restaurante", FormMethod.Post)) {



            <h3 class="central">Pedido</h3>
            @Html.TextBoxFor(m => m.Nome, new { placeholder = "Entre com o nome do cliente", @Class = "form-control", @required = "required" })<br>
            @Html.TextBoxFor(m => m.Mesa, new { placeholder = "Numero da mesa", type="number", name="mesa", @Class = "form-control", @required = "required" }) <br/>
            

            <select class="form-control form-control-lg" id="servicoPrato">
                <option value="nada" class="nada">Selecione o Serviço</option>
                <option value="Pratos">Pratos</option>
            </select>

            <div class="row servicos" id="selecionandoServicoPrato">
                <div class="col-sm-12">
                    @Html.TextBoxFor(m => m.Pratos, new { @Class = "form-control resultadoPrato" })
                    @Html.TextBoxFor(m => m.QtdPratos, new { name = "quantidadeprato", placeholder = "Quantidade", type = "number", @Class = "form-control quantidadePrato" })<br />

                </div>
            </div>

            <select class="form-control form-control-lg" id="servicoBebida">
                <option value="nada" class="nada">Selecione o Serviço</option>
                <option value="Bebidas">Bebidas</option>
            </select>

            <div class="row servicos" id="selecionandoServicoBebida">
                <div class="col-sm-12">
                    @Html.TextBoxFor(m => m.Bebidas, new { @Class = "form-control resultadoBebida" })
                    @Html.TextBoxFor(m => m.QtdBebidas, new { name = "quantidadebebida", placeholder = "Quantidade", type = "number", @Class = "form-control quantidadeBebida" })<br />
                   
                </div>
            </div>

            <select class="form-control form-control-lg" id="servicoSobremesa">
                <option value="nada" class="nada">Selecione o Serviço</option>
                <option value="Sobremesas">Sobremesas</option>
            </select>

            <div class="row servicos" id="selecionandoServicoSobremesa">
                <div class="col-sm-12">
                    @Html.TextBoxFor(m => m.Sobremesas, new { @Class = "form-control resultadoSobremesa" })<br>
                    @Html.TextBoxFor(m => m.QtdSobremesas, new { name = "quantidadesobremesa", placeholder = "Quantidade", type = "number", @Class = "form-control quantidadeSobremesa" })<br />
                </div>
            </div>


            <div class="col-sm-12">
                <div id="button-cadastro">
                    <button class="btn" type="submit" name="btn_cadastro-servico">Salvar</button>
                </div>
            </div>
        }
    </div>
</div>

Restaurante/Views/Restaurante/Pedidos.cshtml
@model IEnumerable<Restaurante.Models.Pedido>
@{
    ViewData["Title"] = "Pedidos Cozinha";
}

<h2>Pedidos</h2>


<table class="table table-dark">
    <tr>
        <th>Mesa do Cliente</th>
        <th>Nome do Cliente</th>
        <th>Pedidos</th>
        <th>Quantidade</th>
        <th>Horario</th>
    </tr>
    @if(Model != null){
    
    @foreach (var pedido in Model) {
    <tr>
        <td>@pedido.Mesa</td>
        <td>@pedido.Nome</td>
        <td>@pedido.Pratos <br>
            @pedido.Bebidas<br>
            @pedido.Sobremesas</td>
        <td>@pedido.QtdPratos  <br> 
            @pedido.QtdBebidas <br>     
            @pedido.QtdSobremesas</td>
        <td>@pedido.Data</td>
        
        

    </tr>
    }
    }

</table>

Restaurante/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Restaurante</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Restaurante</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Pedidos Mesa</a></li>
                    <li><a asp-area="" asp-controller="Restaurante" asp-action="Pedidos">Pedidos Cozinha</a></li>

                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Restaurante</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>